builds:
  - goos:
      - linux
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.date={{.Date}}
    env:
      - CGO_ENABLED=0
archives:
-
  id: archive-no-version
  format: binary
  name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'
  replacements:
    darwin: macOS
    linux: linux
    amd64: 64bit
checksum:
  name_template: checksums.txt
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
